# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-27 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_saver', '0004_media_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='mtype',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
