# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-30 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_saver', '0006_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(default='pic_folder/None/no-img.mp4', upload_to='pic_folder/'),
        ),
    ]
