# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-30 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_saver', '0007_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(default='pic_folder/None/no-img.mp4', upload_to='/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='/'),
        ),
    ]
